(function() {
  'use strict';

  var text1 = "Washington (CNN)House Democrats are seeking a Justice Department investigation of the Trump Foundation, following reports about a large donation he gave to Florida's attorney general in 2013. Trump donated $25,000 to Florida Attorney General Pam Bondi's campaign, as her office was considering whether to open an investigation into Trump University. Bondi's office did not open an investigation, and Trump and Bondi have both said there was no wrongdoing and said the donation was not tied to any favors. These payments may have influenced Mrs. Bondi's official decision not to participate in litigation against Mr. Trump, Democratic members of the House Judiciary Committee wrote in their letter Tuesday to Attorney General Loretta Lynch. The Democrats specifically cite anti-bribery laws in their request.The donation gained new attention following reports that Trump agreed to pay a $2,500 fine to the IRS because he originally gave to Bondi's campaign from his charity, the Trump Foundation. The request also comes as new questions were raised in a Washington Post report about whether Trump has donated as much to charity as he claims. The Trump campaign has repeatedly declined to provide evidence of his donations. Trump running mate Mike Pence told CNN's Wolf Blitzer Monday that Trump has donated millions of dollars to charity.Anyone who knows anything about Donald Trump and his career knows that this is a man who's given away tens of millions of dollars to charitable causes throughout the course of his business life -- he's been incredibly generous Pence said.";
  var text2 = "The billionaire co-founder of LinkedIn, Reid Hoffman, has pledged to give up to $5 million to veterans groups if Donald J. Trump agrees to release his tax returns before the Oct. 19 presidential debate. Mr. Hoffman announced his challenge in a statement published Monday on Medium that said he was offering a matching donation to support a crowdfunding campaign started by Peter Kiernan, a former Marine. By midday Tuesday, Mr. Kiernan’s fund-raising on Crowdpac.com had raised more than $74,000 toward its $1 million goal of donating funds to 10 nonprofit organizations that help war veterans. Mr. Hoffman offered to match those donations 5 to 1 up to $5 million. He said that offer was inspired by Mr. Trump’s own pledge in 2012 to donate that amount to a charity if President Obama revealed his college and passport records and applications. At the time, Mr. Trump had been questioning whether Mr. Obama was born in the United States (indeed he was, in Hawaii).";
  var text3 = "Candidates are not required to release their returns, but if Mr. Trump fails to do so before the election, he would be the first major-party presidential nominee in four decades to withhold them. This has fueled speculation that Mr. Trump’s returns would reveal facts about his wealth, charitable donations, business relationships or tax arrangements that might be politically damaging.";
  var text4 = "Trump campaign policy adviser Stephen Miller told NPR's Sarah McCammon that a Trump administration would focus on fraud to finance the family leave portion. Miller's estimate was $5.3 billion in unemployment insurance fraud, which the campaign believes it can recoup half of. Republicans wary of increasing government spending frequently suggest funding new proposals by saying they will eliminate fraud.";
  var text5 = "The Trump campaign says Trump's daughter Ivanka was deeply involved in coming up with this proposal. It echoes a notable line from her speech at the Republican National Convention in July, when she told Republicans that Trump would focus on making quality child care affordable and accessible for all.";

  module.exports = {
    get() {
      return [text1, text2, text3, text4, text5];
    }
  };

})();
